import React,{useState}from'react';
import{useFleet}from'../context/FleetContext';
import{Truck,Building2,ShieldCheck,Bell,AlertTriangle,LogOut}from'lucide-react';
import{oidcConfigured,signOutOidc}from'../auth/oidcSession';
import{useSecurePrincipal}from'../auth/OidcAuthGate';
import{nativeFleetLogout}from'../auth/nativeAuthClient';
import{GovernmentServicesQuickActions}from'./government/GovernmentServicesQuickActions';

export const Header:React.FC=()=>{const{currentCompany,currentUser,complianceDocs,vehicles}=useFleet();const principal=useSecurePrincipal();const nativeMode=!oidcConfigured&&!!principal;const[alerts,setAlerts]=useState(false);const expired=complianceDocs.filter(d=>d.verificationStatus==='expired').length;const maintenance=vehicles.filter(v=>v.status==='maintenance').length;const total=expired+maintenance;const roleLabel=principal?.role??currentUser.role;const companyLabel=principal?.companyId??currentCompany.name;const logout=()=>{if(oidcConfigured)void signOutOidc();else{nativeFleetLogout();window.location.reload();}};
return <header className="sticky top-0 z-30 border-b border-slate-800 bg-slate-900 text-white shadow-md"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex h-16 items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-600 shadow-lg shadow-blue-500/20"><Truck className="h-6 w-6"/></div><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-display text-xl font-extrabold tracking-tight">Fleet<span className="text-blue-400">OS</span></span><span className="hidden rounded-full border border-blue-500/30 bg-blue-500/20 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-blue-300 sm:inline">ERP Core</span></div><p className="hidden truncate text-xs text-slate-400 md:block">India-first transport operations & telemetry</p></div></div><div className="flex items-center gap-2"><GovernmentServicesQuickActions/><div className="hidden items-center gap-2 rounded-lg border border-slate-700 bg-slate-800/80 px-3 py-1.5 text-xs text-slate-200 sm:flex"><Building2 className="h-3.5 w-3.5 text-blue-400"/><span className="max-w-[150px] truncate">{companyLabel}</span><span className="text-slate-500">•</span><ShieldCheck className="h-3.5 w-3.5 text-teal-400"/><span className="capitalize">{String(roleLabel).replace('_',' ')}</span></div><div className="relative"><button onClick={()=>setAlerts(!alerts)} className="relative rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><Bell className="h-5 w-5"/>{total>0&&<span className="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-[10px] font-bold">{total}</span>}</button>{alerts&&<div className="absolute right-0 z-50 mt-2 w-80 rounded-xl border border-slate-700 bg-slate-800 p-3 shadow-2xl"><div className="border-b border-slate-700 pb-2 text-xs font-semibold uppercase tracking-wider">Fleet alerts <span className="float-right text-[10px] text-slate-400">{total} active</span></div><div className="mt-2 space-y-2">{expired>0&&<div className="flex gap-2 rounded-lg bg-red-500/10 p-2.5 text-xs text-red-300"><AlertTriangle className="h-4 w-4"/><span>{expired} compliance document(s) expired.</span></div>}{maintenance>0&&<div className="flex gap-2 rounded-lg bg-amber-500/10 p-2.5 text-xs text-amber-300"><AlertTriangle className="h-4 w-4"/><span>{maintenance} vehicle(s) in maintenance.</span></div>}{!total&&<div className="py-4 text-center text-xs text-slate-400">No critical warnings.</div>}</div></div>}</div>{(nativeMode||oidcConfigured)&&<button onClick={logout} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-red-300" title="Sign out"><LogOut className="h-4 w-4"/></button>}</div></div></div></header>};
