import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { URL } from 'node:url';
import { normalizeTelemetry, type ProviderTelemetryPayload } from './normalize.js';
import { TelemetryStore } from './store.js';
import { EvidenceStore } from './evidence.js';
import { ProviderRegistry } from './providerRegistry.js';
import { ProviderAdapterError, type ProviderContext } from './providerAdapters.js';
import { TenantAuthorizer, type TenantRole } from './tenantAuth.js';
import { authorizeTenantRequest, canAccessVehicle, canWriteEvidence } from './tenantAccess.js';
import { createTelemetryHistoryRepository } from './telemetryHistory.js';
import { createSettlementRepository } from './settlementRepository.js';
import { createTripAccessRepository } from './tripAccessRepository.js';
import { NativeAuthService } from './nativeAuth.js';
import { OnboardingService } from './onboarding.js';
import { getDeploymentReadiness } from './deploymentReadiness.js';
const port=Number(process.env.PORT??8787),ingestToken=process.env.FLEETOS_INGEST_TOKEN?.trim()??'',allowedOrigin=process.env.FLEETOS_WEB_ORIGIN?.trim()??'';const store=new TelemetryStore(),evidenceStore=new EvidenceStore(),providerRegistry=new ProviderRegistry(),tenantAuthorizer=new TenantAuthorizer(),historyRepository=createTelemetryHistoryRepository(),settlementRepository=createSettlementRepository(),tripAccessRepository=createTripAccessRepository(),nativeAuth=new NativeAuthService();const onboarding=nativeAuth.enabled?new OnboardingService(nativeAuth):null;const RESTRICTED_WORKER_ROLES=new Set<TenantRole>(['driver','khalashi']);
function applyCors(req:IncomingMessage,res:ServerResponse){if(!allowedOrigin)return;const origin=req.headers.origin;if(origin===allowedOrigin){res.setHeader('Access-Control-Allow-Origin',allowedOrigin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type, X-FleetOS-Platform-Admin-Token');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');}}
function sendJson(req:IncomingMessage,res:ServerResponse,status:number,body:unknown){applyCors(req,res);res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body));}
async function readJson(req:IncomingMessage,limit=1024*1024):Promise<unknown>{const chunks:Buffer[]=[];let size=0;for await(const chunk of req){const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=b.length;if(size>limit)throw new Error('request body too large');chunks.push(b);}if(!chunks.length)return{};return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown;}
function bearerToken(req:IncomingMessage){const h=req.headers.authorization??'';return h.startsWith('Bearer ')?h.slice(7).trim():'';}function platformAdminToken(req:IncomingMessage){const v=req.headers['x-fleetos-platform-admin-token'];return Array.isArray(v)?v[0]??'':v??'';}function platformApplicationIdFromPath(p:string){const a='/api/platform/applications/',b='/approve';if(!p.startsWith(a)||!p.endsWith(b))return undefined;const e=p.slice(a.length,-b.length).replace(/^\/+|\/+$/g,'');return!e||e.includes('/')?undefined:decodeURIComponent(e).trim()||undefined;}function authUserIdFromPath(p:string){const prefix='/api/auth/users/';if(!p.startsWith(prefix))return undefined;const encoded=p.slice(prefix.length).replace(/^\/+|\/+$/g,'');return!encoded||encoded.includes('/')?undefined:decodeURIComponent(encoded).trim()||undefined;}function requestHeaders(req:IncomingMessage):ProviderContext['headers']{return Object.fromEntries(Object.entries(req.headers));}function isRestrictedWorker(role:TenantRole){return RESTRICTED_WORKER_ROLES.has(role);}async function persistReading(reading:ReturnType<typeof normalizeTelemetry>){store.upsert(reading);await historyRepository.append(reading);}
const server=createServer(async(req,res)=>{try{const method=req.method??'GET',url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);if(method==='OPTIONS'){applyCors(req,res);res.statusCode=204;return res.end();}if(method==='GET'&&url.pathname==='/health')return sendJson(req,res,200,{ok:true,service:'fleetos-telemetry',providersConfigured:providerRegistry.list().length,tenantReadPrincipalsConfigured:tenantAuthorizer.configuredCount,jwtEnabled:tenantAuthorizer.jwtEnabled,oidcEnabled:tenantAuthorizer.oidcEnabled,nativeAuthEnabled:nativeAuth.enabled,onboardingEnabled:Boolean(onboarding),telemetryHistoryRepository:historyRepository.kind,settlementRepository:settlementRepository.kind,tripAccessRepository:tripAccessRepository.kind,evidenceStorage:evidenceStore.storageKind});if(method==='GET'&&url.pathname==='/ready'){const r=getDeploymentReadiness();return sendJson(req,res,r.readyForProduction?200:503,r);}if(method==='GET'&&url.pathname==='/api/providers')return sendJson(req,res,200,{providers:providerRegistry.list()});
if(method==='POST'&&url.pathname==='/api/onboarding/companies'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,201,{application:await onboarding.submitCompany(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/drivers'){if(!onboarding)return sendJson(req,res,503,{error:'driver onboarding is not configured'});return sendJson(req,res,201,{driver:await onboarding.registerDriver(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/activate-owner'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,201,{account:await onboarding.activateOwner(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/link-driver'){if(!onboarding)return sendJson(req,res,503,{error:'driver onboarding is not configured'});const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});return sendJson(req,res,200,{driver:await onboarding.linkDriver(await readJson(req),a.principal)});}if(method==='GET'&&url.pathname==='/api/platform/applications'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,200,{applications:await onboarding.listApplications(platformAdminToken(req))});}const approvalId=method==='POST'?platformApplicationIdFromPath(url.pathname):undefined;if(approvalId){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});const approval=await onboarding.approveApplication(approvalId,platformAdminToken(req)),activationUrl=allowedOrigin?`${allowedOrigin}/?activate-company=1&applicationId=${encodeURIComponent(approval.application.id)}&token=${encodeURIComponent(approval.activationToken)}`:undefined;return sendJson(req,res,200,{approval,activationUrl});}
if(method==='POST'&&url.pathname==='/api/auth/login'){try{return sendJson(req,res,200,await nativeAuth.login(await readJson(req)));}catch(e){const m=e instanceof Error?e.message:'sign-in failed';return sendJson(req,res,m.includes('not configured')?503:401,{error:m});}}
if(url.pathname==='/api/auth/users'&&(method==='GET'||method==='POST')){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});if(method==='GET')return sendJson(req,res,200,{companyId:a.principal.companyId,users:await nativeAuth.listUsers(a.principal)});return sendJson(req,res,201,{user:await nativeAuth.createUser(await readJson(req),a.principal)});}const managedUserId=method==='PATCH'?authUserIdFromPath(url.pathname):undefined;if(managedUserId){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});return sendJson(req,res,200,{user:await nativeAuth.manageUser(managedUserId,await readJson(req),a.principal)});}
if(method==='GET'&&url.pathname==='/api/me'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const{sub,companyId,role}=a.principal;return sendJson(req,res,200,{principal:{sub,companyId,role}});}if(method==='GET'&&url.pathname==='/api/me/trips'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const assignments=await tripAccessRepository.listForPrincipal(a.principal);return sendJson(req,res,200,{companyId:a.principal.companyId,trips:assignments.map(({tripId,vehicleId,updatedAt})=>({tripId,vehicleId,updatedAt}))});}
if(method==='POST'&&url.pathname==='/api/telemetry/ingest'){if(!ingestToken)return sendJson(req,res,503,{error:'ingest token is not configured'});if(bearerToken(req)!==ingestToken)return sendJson(req,res,401,{error:'unauthorized'});const reading=normalizeTelemetry(await readJson(req) as ProviderTelemetryPayload);await persistReading(reading);return sendJson(req,res,202,{accepted:true,reading});}
const providerMatch=url.pathname.match(/^\/api\/providers\/([^/]+)\/ingest$/);if(method==='POST'&&providerMatch){const providerId=decodeURIComponent(providerMatch[1]);const context:ProviderContext={headers:requestHeaders(req),query:url.searchParams};try{const readings=providerRegistry.normalize(providerId,await readJson(req),context);for(const reading of readings)await persistReading(reading);return sendJson(req,res,202,{accepted:true,providerId,count:readings.length});}catch(e){if(e instanceof ProviderAdapterError)return sendJson(req,res,e.status,{error:e.message});throw e;}}
const authorization=await authorizeTenantRequest(req,tenantAuthorizer);if(!authorization.ok)return sendJson(req,res,authorization.status,{error:authorization.error});const principal=authorization.principal;
if(method==='GET'&&url.pathname==='/api/telemetry/latest'){if(isRestrictedWorker(principal.role))return sendJson(req,res,403,{error:'worker accounts cannot browse company-wide telemetry'});const vehicleId=url.searchParams.get('vehicleId')?.trim();if(vehicleId&&!await canAccessVehicle(principal,vehicleId,tripAccessRepository))return sendJson(req,res,403,{error:'vehicle access denied'});return sendJson(req,res,200,{companyId:principal.companyId,readings:store.latest(principal.companyId,vehicleId||undefined)});}if(method==='GET'&&url.pathname==='/api/telemetry/history'){if(isRestrictedWorker(principal.role))return sendJson(req,res,403,{error:'worker accounts cannot browse company-wide telemetry history'});const vehicleId=url.searchParams.get('vehicleId')?.trim();if(vehicleId&&!await canAccessVehicle(principal,vehicleId,tripAccessRepository))return sendJson(req,res,403,{error:'vehicle access denied'});const limit=Math.max(1,Math.min(Number(url.searchParams.get('limit')??100),500));return sendJson(req,res,200,{companyId:principal.companyId,readings:await historyRepository.list(principal.companyId,vehicleId||undefined,limit)});}if(method==='GET'&&url.pathname==='/api/settlements'){if(principal.role!=='owner'&&principal.role!=='manager'&&principal.role!=='accountant')return sendJson(req,res,403,{error:'finance access denied'});return sendJson(req,res,200,{companyId:principal.companyId,settlements:await settlementRepository.list(principal.companyId)});}if(method==='GET'&&url.pathname==='/api/trip-assignments'){if(principal.role!=='owner'&&principal.role!=='manager'&&principal.role!=='dispatcher')return sendJson(req,res,403,{error:'trip assignment access denied'});return sendJson(req,res,200,{companyId:principal.companyId,assignments:await tripAccessRepository.listCompany(principal.companyId)});}if(method==='POST'&&url.pathname==='/api/evidence'){if(!canWriteEvidence(principal))return sendJson(req,res,403,{error:'evidence write access denied'});const body=await readJson(req) as Record<string,unknown>,tripId=String(body.tripId??'').trim(),vehicleId=String(body.vehicleId??'').trim();if(!tripId||!vehicleId)return sendJson(req,res,400,{error:'tripId and vehicleId are required'});if(!await canAccessVehicle(principal,vehicleId,tripAccessRepository))return sendJson(req,res,403,{error:'vehicle access denied'});return sendJson(req,res,201,{evidence:await evidenceStore.put(principal.companyId,tripId,vehicleId,body)});}return sendJson(req,res,404,{error:'not found'});}catch(e){console.error(e);return sendJson(req,res,400,{error:e instanceof Error?e.message:'request failed'});}});
nativeAuth.bootstrapFromEnv().catch(e=>{console.error('FleetOS native auth bootstrap failed:',e);process.exit(1);});server.listen(port,()=>console.log(`FleetOS telemetry server listening on ${port}`));
