import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { normalizeTelemetry, TelemetryStore, type ProviderTelemetryPayload } from './telemetry.js';
import { createTelemetryRepository } from './telemetryRepository.js';
import { registerConfiguredProviders } from './providers/config.js';
import { ProviderRegistry } from './providers/registry.js';
import type { ProviderContext } from './providers/types.js';
import { TenantAuthorizer, type TenantRole } from './tenantAuth.js';
import { authorizeRoleRequest, authorizeTenantRequest } from './httpAuthorization.js';
import { EvidenceStore } from './evidence.js';
import { createSettlementRepository, normalizeSettlementTerms } from './settlementRepository.js';
import { createTripAccessRepository, normalizeTripAssignment } from './tripAccessRepository.js';
import { getDeploymentReadiness } from './deploymentReadiness.js';
import { NativeAuthService } from './nativeAuth.js';
import { OnboardingService } from './onboarding.js';

const port = Number(process.env.PORT ?? 8787);
const ingestToken = process.env.FLEETOS_INGEST_TOKEN ?? '';
const allowedOrigin = process.env.FLEETOS_WEB_ORIGIN?.trim() ?? '';
const store = new TelemetryStore();
const historyRepository = createTelemetryRepository();
const settlementRepository = createSettlementRepository();
const tripAccessRepository = createTripAccessRepository();
const providerRegistry = new ProviderRegistry();
const tenantAuthorizer = new TenantAuthorizer();
const evidenceStore = new EvidenceStore();
const nativeAuth = new NativeAuthService();
const onboarding = process.env.DATABASE_URL?.trim() ? new OnboardingService(nativeAuth) : null;
registerConfiguredProviders(providerRegistry);
const FINANCE_ROLES = new Set<TenantRole>(['owner','manager','accountant']);
const ASSIGNMENT_ROLES = new Set<TenantRole>(['owner','manager','dispatcher']);
const RESTRICTED_WORKER_ROLES = new Set<TenantRole>(['driver','khalashi']);
function applyCors(req:IncomingMessage,res:ServerResponse){const origin=req.headers.origin;if(!origin||!allowedOrigin||origin!==allowedOrigin)return;res.setHeader('access-control-allow-origin',origin);res.setHeader('vary','Origin');res.setHeader('access-control-allow-methods','GET,POST,PUT,PATCH,OPTIONS');res.setHeader('access-control-allow-headers','Authorization,Content-Type,Accept,X-FleetOS-Company-Id,X-File-Name,X-FleetOS-Platform-Admin-Token');res.setHeader('access-control-max-age','600');}
function sendJson(req:IncomingMessage,res:ServerResponse,status:number,body:unknown){applyCors(req,res);res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify(body));}
async function readJson(req:IncomingMessage):Promise<unknown>{const chunks:Buffer[]=[];let total=0;for await(const chunk of req){const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=b.length;if(total>256*1024)throw new Error('payload too large');chunks.push(b);}return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown:null;}
function bearerToken(req:IncomingMessage){const h=req.headers.authorization??'';return h.startsWith('Bearer ')?h.slice(7):'';}function platformAdminToken(req:IncomingMessage){const v=req.headers['x-fleetos-platform-admin-token'];return Array.isArray(v)?v[0]??'':v??'';}function providerIdFromPath(p:string){const a='/api/providers/',b='/ingest';if(!p.startsWith(a)||!p.endsWith(b))return undefined;const e=p.slice(a.length,-b.length);return e?decodeURIComponent(e):undefined;}function settlementVehicleIdFromPath(p:string){const a='/api/finance/settlement-terms/';if(!p.startsWith(a))return undefined;const e=p.slice(a.length);return!e||e.includes('/')?undefined:decodeURIComponent(e).trim()||undefined;}function tripIdFromAssignmentPath(p:string){const a='/api/trips/',b='/assignment';if(!p.startsWith(a)||!p.endsWith(b))return undefined;const e=p.slice(a.length,-b.length).replace(/^\/+|\/+$/g,'');return!e||e.includes('/')?undefined:decodeURIComponent(e).trim()||undefined;}function platformApplicationIdFromPath(p:string){const a='/api/platform/applications/',b='/approve';if(!p.startsWith(a)||!p.endsWith(b))return undefined;const e=p.slice(a.length,-b.length).replace(/^\/+|\/+$/g,'');return!e||e.includes('/')?undefined:decodeURIComponent(e).trim()||undefined;}function authUserIdFromPath(p:string){const a='/api/auth/users/';if(!p.startsWith(a))return undefined;const e=p.slice(a.length).replace(/^\/+|\/+$/g,'');return!e||e.includes('/')?undefined:decodeURIComponent(e).trim()||undefined;}function requestHeaders(req:IncomingMessage):ProviderContext['headers']{return Object.fromEntries(Object.entries(req.headers));}function isRestrictedWorker(role:TenantRole){return RESTRICTED_WORKER_ROLES.has(role);}async function persistReading(reading:ReturnType<typeof normalizeTelemetry>){store.upsert(reading);await historyRepository.append(reading);}
const server=createServer(async(req,res)=>{try{const method=req.method??'GET',url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);if(method==='OPTIONS'){applyCors(req,res);res.statusCode=204;return res.end();}
if(method==='GET'&&url.pathname==='/health')return sendJson(req,res,200,{ok:true,service:'fleetos-telemetry',providersConfigured:providerRegistry.list().length,tenantReadPrincipalsConfigured:tenantAuthorizer.configuredCount,jwtEnabled:tenantAuthorizer.jwtEnabled,oidcEnabled:tenantAuthorizer.oidcEnabled,nativeAuthEnabled:nativeAuth.enabled,onboardingEnabled:Boolean(onboarding),telemetryHistoryRepository:historyRepository.kind,settlementRepository:settlementRepository.kind,tripAccessRepository:tripAccessRepository.kind,evidenceStorage:evidenceStore.storageKind});
if(method==='GET'&&url.pathname==='/ready'){const r=getDeploymentReadiness();return sendJson(req,res,r.readyForProduction?200:503,r);}if(method==='GET'&&url.pathname==='/api/providers')return sendJson(req,res,200,{providers:providerRegistry.list()});
if(method==='POST'&&url.pathname==='/api/onboarding/companies'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,201,{application:await onboarding.submitCompany(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/drivers'){if(!onboarding)return sendJson(req,res,503,{error:'driver onboarding is not configured'});return sendJson(req,res,201,{driver:await onboarding.registerDriver(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/activate-owner'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,201,{account:await onboarding.activateOwner(await readJson(req))});}if(method==='POST'&&url.pathname==='/api/onboarding/link-driver'){if(!onboarding)return sendJson(req,res,503,{error:'driver onboarding is not configured'});const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});return sendJson(req,res,200,{driver:await onboarding.linkDriver(await readJson(req),a.principal)});}if(method==='GET'&&url.pathname==='/api/platform/applications'){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});return sendJson(req,res,200,{applications:await onboarding.listApplications(platformAdminToken(req))});}const approvalId=method==='POST'?platformApplicationIdFromPath(url.pathname):undefined;if(approvalId){if(!onboarding)return sendJson(req,res,503,{error:'company onboarding is not configured'});const approval=await onboarding.approveApplication(approvalId,platformAdminToken(req)),activationUrl=allowedOrigin?`${allowedOrigin}/?activate-company=1&applicationId=${encodeURIComponent(approval.application.id)}&token=${encodeURIComponent(approval.activationToken)}`:undefined;return sendJson(req,res,200,{approval,activationUrl});}
if(method==='POST'&&url.pathname==='/api/auth/login'){try{return sendJson(req,res,200,await nativeAuth.login(await readJson(req)));}catch(error){const message=error instanceof Error?error.message:'sign-in failed';return sendJson(req,res,message.includes('not configured')?503:401,{error:message});}}
if(url.pathname==='/api/auth/users'&&(method==='GET'||method==='POST')){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});if(method==='GET')return sendJson(req,res,200,{companyId:a.principal.companyId,users:await nativeAuth.listUsers(a.principal)});return sendJson(req,res,201,{user:await nativeAuth.createUser(await readJson(req),a.principal)});}const managedUserId=method==='PATCH'?authUserIdFromPath(url.pathname):undefined;if(managedUserId){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});return sendJson(req,res,200,{user:await nativeAuth.manageUser(managedUserId,await readJson(req),a.principal)});}
if(method==='GET'&&url.pathname==='/api/me'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const{sub,companyId,role}=a.principal;return sendJson(req,res,200,{principal:{sub,companyId,role}});}if(method==='GET'&&url.pathname==='/api/me/trips'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const assignments=await tripAccessRepository.listForPrincipal(a.principal);return sendJson(req,res,200,{companyId:a.principal.companyId,trips:assignments.map(({tripId,vehicleId,updatedAt})=>({tripId,vehicleId,updatedAt}))});}
if(method==='POST'&&url.pathname==='/api/telemetry/ingest'){if(!ingestToken)return sendJson(req,res,503,{error:'ingest token is not configured'});if(bearerToken(req)!==ingestToken)return sendJson(req,res,401,{error:'unauthorized'});const reading=normalizeTelemetry(await readJson(req) as ProviderTelemetryPayload);await persistReading(reading);return sendJson(req,res,202,{accepted:true,reading});}const providerId=method==='POST'?providerIdFromPath(url.pathname):undefined;if(providerId){if(!ingestToken)return sendJson(req,res,503,{error:'ingest token is not configured'});if(bearerToken(req)!==ingestToken)return sendJson(req,res,401,{error:'unauthorized'});const adapter=providerRegistry.resolve(providerId);if(!adapter)return sendJson(req,res,404,{error:'provider adapter is not configured',providerId});const context:ProviderContext={providerId,kind:adapter.kind,receivedAt:new Date().toISOString(),headers:requestHeaders(req)};const normalized=adapter.toTelemetry(await readJson(req),context).map(r=>normalizeTelemetry(r));for(const reading of normalized)await persistReading(reading);return sendJson(req,res,202,{accepted:true,providerId,count:normalized.length,readings:normalized});}
if(method==='GET'&&url.pathname==='/api/telemetry/live'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});let vehicles=store.list(a.principal.companyId);if(isRestrictedWorker(a.principal.role)){const assignments=await tripAccessRepository.listForPrincipal(a.principal),allowed=new Set(assignments.map(r=>r.vehicleId).filter((id):id is string=>Boolean(id)));vehicles=vehicles.filter(r=>allowed.has(r.vehicleId));}return sendJson(req,res,200,{companyId:a.principal.companyId,vehicles,generatedAt:new Date().toISOString()});}if(method==='GET'&&url.pathname.startsWith('/api/telemetry/live/')){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const vehicleId=decodeURIComponent(url.pathname.slice('/api/telemetry/live/'.length));if(isRestrictedWorker(a.principal.role)&&!await tripAccessRepository.canAccessVehicle(a.principal,vehicleId))return sendJson(req,res,404,{error:'vehicle not found'});const reading=store.get(a.principal.companyId,vehicleId);return reading?sendJson(req,res,200,reading):sendJson(req,res,404,{error:'no telemetry available for vehicle in this tenant'});}
if(method==='GET'&&url.pathname==='/api/telemetry/history'){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const vehicleId=url.searchParams.get('vehicleId')?.trim()||undefined;if(isRestrictedWorker(a.principal.role)){if(!vehicleId)return sendJson(req,res,403,{error:'worker telemetry history requires an assigned vehicle'});if(!await tripAccessRepository.canAccessVehicle(a.principal,vehicleId))return sendJson(req,res,404,{error:'vehicle not found'});}const limit=Math.min(Math.max(Number(url.searchParams.get('limit')??200),1),1000);return sendJson(req,res,200,{companyId:a.principal.companyId,vehicleId,readings:await historyRepository.list(a.principal.companyId,vehicleId,limit)});}
if(method==='GET'&&url.pathname==='/api/finance/settlement-terms'){const a=await authorizeRoleRequest(req,tenantAuthorizer,FINANCE_ROLES,'finance access denied');if(!a.ok)return sendJson(req,res,a.status,{error:a.error});return sendJson(req,res,200,{companyId:a.principal.companyId,settlements:await settlementRepository.list(a.principal.companyId)});}const settlementVehicleId=method==='PUT'?settlementVehicleIdFromPath(url.pathname):undefined;if(settlementVehicleId){const a=await authorizeRoleRequest(req,tenantAuthorizer,FINANCE_ROLES,'finance access denied');if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const terms=normalizeSettlementTerms(a.principal.companyId,settlementVehicleId,await readJson(req) as never,a.principal.sub);return sendJson(req,res,200,{settlement:await settlementRepository.upsert(terms)});}
const tripId=method==='PUT'?tripIdFromAssignmentPath(url.pathname):undefined;if(tripId){const a=await authorizeRoleRequest(req,tenantAuthorizer,ASSIGNMENT_ROLES,'trip assignment access denied');if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const assignment=normalizeTripAssignment(a.principal.companyId,tripId,await readJson(req) as never,a.principal.sub);return sendJson(req,res,200,{assignment:await tripAccessRepository.upsert(assignment)});}
const evidenceMatch=url.pathname.match(/^\/api\/trips\/([^/]+)\/evidence$/);if(evidenceMatch&&(method==='GET'||method==='POST')){const a=await authorizeTenantRequest(req,tenantAuthorizer);if(!a.ok)return sendJson(req,res,a.status,{error:a.error});const tripId=decodeURIComponent(evidenceMatch[1]);if(!await tripAccessRepository.canAccess(a.principal,tripId))return sendJson(req,res,404,{error:'trip not found'});if(method==='GET')return sendJson(req,res,200,{companyId:a.principal.companyId,tripId,evidence:await evidenceStore.list(a.principal.companyId,tripId)});const evidenceType=String(req.headers['x-evidence-type']??url.searchParams.get('type')??'other');return sendJson(req,res,201,{evidence:await evidenceStore.upload(req,a.principal,tripId,evidenceType)});}return sendJson(req,res,404,{error:'not found'});}catch(error){console.error(error);return sendJson(req,res,400,{error:error instanceof Error?error.message:'request failed'});}});
nativeAuth.bootstrapFromEnv().catch(error=>{console.error('FleetOS native auth bootstrap failed:',error);process.exit(1);});server.listen(port,()=>console.log(`FleetOS telemetry server listening on ${port}`));
