import { createHmac, timingSafeEqual } from 'node:crypto';
import type { IncomingMessage } from 'node:http';
import { createRemoteJWKSet, jwtVerify, type JWTPayload } from 'jose';
import { Pool } from 'pg';

export type TenantRole = 'owner' | 'manager' | 'dispatcher' | 'driver' | 'khalashi' | 'accountant' | 'compliance';
export interface TenantPrincipal { sub:string; companyId:string; role:TenantRole; }
interface TokenConfigEntry { token:string; companyId:string; role?:TenantRole; sub?:string; }
interface JwtClaims { sub?:unknown; companyId?:unknown; role?:unknown; exp?:unknown; nbf?:unknown; iss?:unknown; aud?:unknown; }
const ROLES=new Set<TenantRole>(['owner','manager','dispatcher','driver','khalashi','accountant','compliance']);
function decodeBase64Url(value:string):Buffer{return Buffer.from(value.replace(/-/g,'+').replace(/_/g,'/'),'base64');}
function safeJson(value:Buffer):unknown{return JSON.parse(value.toString('utf8')) as unknown;}
function verifyHs256(token:string,secret:string):JwtClaims|null{const parts=token.split('.');if(parts.length!==3)return null;const[headerPart,payloadPart,signaturePart]=parts;let header:unknown,claims:unknown;try{header=safeJson(decodeBase64Url(headerPart));claims=safeJson(decodeBase64Url(payloadPart));}catch{return null;}if(!header||typeof header!=='object'||(header as Record<string,unknown>).alg!=='HS256'||!claims||typeof claims!=='object')return null;const expected=createHmac('sha256',secret).update(`${headerPart}.${payloadPart}`).digest(),supplied=decodeBase64Url(signaturePart);if(expected.length!==supplied.length||!timingSafeEqual(expected,supplied))return null;return claims as JwtClaims;}
function asRole(value:unknown):TenantRole|null{return typeof value==='string'&&ROLES.has(value as TenantRole)?value as TenantRole:null;}
function audienceMatches(claim:unknown,expected:string):boolean{if(!expected)return true;if(typeof claim==='string')return claim===expected;return Array.isArray(claim)&&claim.some(item=>item===expected);}
function bearer(req:IncomingMessage):string{const header=req.headers.authorization??'';return header.startsWith('Bearer ')?header.slice(7).trim():'';}
function claim(payload:JWTPayload,name:string):unknown{return(payload as Record<string,unknown>)[name];}
export class TenantAuthorizer{
 private readonly byToken=new Map<string,TenantPrincipal>();private readonly jwtSecret=process.env.FLEETOS_JWT_SECRET?.trim()??'';private readonly issuer=process.env.FLEETOS_JWT_ISSUER?.trim()??'';private readonly audience=process.env.FLEETOS_JWT_AUDIENCE?.trim()??'';private readonly allowDevTokens=process.env.FLEETOS_ALLOW_DEV_TOKENS==='true';private readonly oidcJwksUrl=process.env.FLEETOS_OIDC_JWKS_URL?.trim()??'';private readonly oidcIssuer=process.env.FLEETOS_OIDC_ISSUER?.trim()??'';private readonly oidcAudience=process.env.FLEETOS_OIDC_AUDIENCE?.trim()??'';private readonly oidcCompanyClaim=process.env.FLEETOS_OIDC_COMPANY_CLAIM?.trim()||'companyId';private readonly oidcRoleClaim=process.env.FLEETOS_OIDC_ROLE_CLAIM?.trim()||'role';private readonly remoteJwks=this.oidcJwksUrl?createRemoteJWKSet(new URL(this.oidcJwksUrl)):null;private readonly nativePool=process.env.DATABASE_URL?.trim()?new Pool({connectionString:process.env.DATABASE_URL!.trim(),max:4}):null;
 constructor(rawConfig=process.env.FLEETOS_TENANT_READ_TOKENS_JSON?.trim()??''){if(!rawConfig)return;const parsed=JSON.parse(rawConfig) as unknown;if(!Array.isArray(parsed))throw new Error('FLEETOS_TENANT_READ_TOKENS_JSON must be a JSON array');for(const item of parsed){const entry=item as Partial<TokenConfigEntry>;if(!entry.token?.trim()||!entry.companyId?.trim())throw new Error('tenant token entries require token and companyId');const role=entry.role??'manager';if(!ROLES.has(role))throw new Error(`unsupported tenant role: ${String(role)}`);this.byToken.set(entry.token.trim(),{sub:entry.sub?.trim()||`dev:${entry.companyId.trim()}`,companyId:entry.companyId.trim(),role});}}
 private principalFromLocalJwt(token:string,now:Date):TenantPrincipal|null{if(!this.jwtSecret)return null;const claims=verifyHs256(token,this.jwtSecret);if(!claims)return null;const sub=typeof claims.sub==='string'?claims.sub.trim():'',companyId=typeof claims.companyId==='string'?claims.companyId.trim():'',role=asRole(claims.role),nowSec=Math.floor(now.getTime()/1000),exp=typeof claims.exp==='number'?claims.exp:null,nbf=typeof claims.nbf==='number'?claims.nbf:null,issuerOk=!this.issuer||claims.iss===this.issuer,audienceOk=audienceMatches(claims.aud,this.audience);return sub&&companyId&&role&&issuerOk&&audienceOk&&(exp===null||exp>nowSec)&&(nbf===null||nbf<=nowSec)?{sub,companyId,role}:null;}
 authenticate(req:IncomingMessage,now=new Date()):TenantPrincipal|null{const token=bearer(req);if(!token)return null;const local=this.principalFromLocalJwt(token,now);if(local)return local;return this.allowDevTokens?(this.byToken.get(token)??null):null;}
 private async nativePrincipalStillValid(principal:TenantPrincipal):Promise<boolean>{if(!this.nativePool)return true;try{const result=await this.nativePool.query('SELECT company_id,role,active FROM fleetos_auth_users WHERE id=$1 LIMIT 1',[principal.sub]);if(!result.rows.length)return false;const row=result.rows[0] as Record<string,unknown>;return Boolean(row.active)&&String(row.company_id)===principal.companyId&&String(row.role)===principal.role;}catch(error){if(error&&typeof error==='object'&&(error as{code?:string}).code==='42P01')return false;throw error;}}
 async authenticateAsync(req:IncomingMessage,now=new Date()):Promise<TenantPrincipal|null>{const token=bearer(req);if(!token)return null;const local=this.principalFromLocalJwt(token,now);if(local)return await this.nativePrincipalStillValid(local)?local:null;if(this.allowDevTokens){const dev=this.byToken.get(token);if(dev)return dev;}if(!this.remoteJwks)return null;try{const{payload}=await jwtVerify(token,this.remoteJwks,{issuer:this.oidcIssuer||undefined,audience:this.oidcAudience||undefined,currentDate:now});const sub=typeof payload.sub==='string'?payload.sub.trim():'',companyRaw=claim(payload,this.oidcCompanyClaim),roleRaw=claim(payload,this.oidcRoleClaim),companyId=typeof companyRaw==='string'?companyRaw.trim():'',role=asRole(roleRaw);return sub&&companyId&&role?{sub,companyId,role}:null;}catch{return null;}}
 get configuredCount():number{return this.byToken.size;}get jwtEnabled():boolean{return Boolean(this.jwtSecret||this.remoteJwks);}get oidcEnabled():boolean{return Boolean(this.remoteJwks);}
}
