import React, { useEffect, useState } from 'react';
import { getFleetAccessToken } from './runtimeSession';
import type { SecurePrincipal } from './securePrincipal';

type ManagedRole = 'manager' | 'dispatcher' | 'driver' | 'khalashi' | 'accountant' | 'compliance';
type ManagedUser = { id:string; email:string; companyId:string; role:ManagedRole|'owner'; displayName:string; active:boolean };
const API_URL=(import.meta.env.VITE_TELEMETRY_API_URL as string|undefined)?.replace(/\/$/,'')||'';
async function api(path:string,init:RequestInit={}){const token=getFleetAccessToken();if(!token)throw new Error('Sign in again');const response=await fetch(`${API_URL}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed');return data;}
export const CompanyUserManagement:React.FC<{principal:SecurePrincipal|null}>=({principal})=>{
 const[users,setUsers]=useState<ManagedUser[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const canView=principal?.role==='owner'||principal?.role==='manager'; const canCreate=principal?.role==='owner';
 const load=async()=>{if(!canView)return;try{setError('');const data=await api('/api/auth/users');setUsers(data.users||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load users');}};
 useEffect(()=>{void load();},[principal?.companyId,principal?.role]);
 if(!canView)return null;
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!canCreate)return;setBusy(true);setError('');setMessage('');const form=e.currentTarget,data=new FormData(form);try{await api('/api/auth/users',{method:'POST',body:JSON.stringify({displayName:String(data.get('displayName')||''),email:String(data.get('email')||''),password:String(data.get('password')||''),role:String(data.get('role')||'')})});form.reset();setMessage('Company account created. Share the credentials securely with that staff member.');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create user');}finally{setBusy(false);}};
 return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
  <div><h2 className="text-lg font-bold">Company access</h2><p className="mt-1 text-xs text-slate-500">Accounts below are restricted to company {principal?.companyId}. Managers can view the directory; only the owner can create accounts.</p></div>
  {error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</div>}{message&&<div className="mt-4 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{message}</div>}
  {canCreate&&<form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="displayName" required placeholder="Full name" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm dark:border-slate-700"/><input name="email" type="email" required placeholder="Work email" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm dark:border-slate-700"/><select name="role" required className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm dark:border-slate-700"><option value="manager">Manager</option><option value="dispatcher">Dispatcher</option><option value="accountant">Accountant</option><option value="compliance">Compliance</option><option value="driver">Driver</option><option value="khalashi">Khalashi</option></select><input name="password" type="password" minLength={10} required placeholder="Temporary password (10+ chars)" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm dark:border-slate-700"/><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50 sm:col-span-2">{busy?'Creating…':'Create company account'}</button></form>}
  <div className="mt-5 grid gap-2">{users.map(user=><div key={user.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-800"><div className="min-w-0"><div className="truncate font-semibold">{user.displayName||user.email}</div><div className="truncate text-xs text-slate-500">{user.email}</div></div><div className="text-right"><div className="text-xs font-bold uppercase">{user.role}</div><div className={`text-[11px] ${user.active?'text-emerald-600':'text-red-500'}`}>{user.active?'Active':'Disabled'}</div></div></div>)}{!users.length&&!error&&<p className="text-sm text-slate-500">No company users found.</p>}</div>
 </section>;
};
